version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - back/express/.env
    environment:
      - PORT=3000
    # Se precisar apontar URL da API no front em runtime, use VITE_API_URL
