AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Validador de Entrega - API Mínima'

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 256

Resources:
  # DynamoDB Table
  DeliveryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: invoiceNumber
          AttributeType: S
      KeySchema:
        - AttributeName: invoiceNumber
          KeyType: HASH

  # Lambda Function
  ValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: index.handler
      Environment:
        Variables:
          DELIVERY_TABLE: !Ref DeliveryTable
          CORS_ORIGIN: '*'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DeliveryTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MyApi

  # API Gateway
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: 'URL da API'
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod'