apiVersion: v1
kind: Secret
metadata:
  name: validador-supabase
  namespace: validador
type: Opaque
stringData:
  SUPABASE_URL: "<preencha-supabase-url>"
  SUPABASE_SERVICE_KEY: "<preencha-service-key>"

