apiVersion: v1
kind: Service
metadata:
  name: validador-app
  namespace: validador
  labels:
    app: validador-app
spec:
  type: ClusterIP
  selector:
    app: validador-app
  ports:
    - name: http
      port: 80
      targetPort: 3000

